/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#7c3aed",
        "primary": "#630ed4",
        "inverse-on-surface": "#ebf1ff",
        "secondary-fixed": "#dae1ff",
        "inverse-primary": "#d2bbff",
        "on-surface": "#151c27",
        "secondary-container": "#ced9ff",
        "on-primary": "#ffffff",
        "tertiary-container": "#a15100",
        "surface-container-highest": "#dce2f3",
        "tertiary": "#7d3d00",
        "on-secondary-fixed-variant": "#3b4665",
        "on-secondary-fixed": "#0f1a37",
        "primary-fixed": "#eaddff",
        "background": "#f9f9ff",
        "on-error-container": "#93000a",
        "surface": "#f9f9ff",
        "on-tertiary-fixed": "#301400",
        "inverse-surface": "#2a313d",
        "surface-container-low": "#f0f3ff",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-secondary-container": "#545e7f",
        "on-secondary": "#ffffff",
        "secondary": "#535d7e",
        "on-tertiary-fixed-variant": "#713700",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#d2bbff",
        "secondary-fixed-dim": "#bbc5eb",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#ede0ff",
        "outline": "#7b7487",
        "outline-variant": "#ccc3d8",
        "tertiary-fixed-dim": "#ffb784",
        "on-surface-variant": "#4a4455",
        "on-background": "#151c27",
        "surface-container": "#e7eefe",
        "on-primary-fixed": "#25005a",
        "on-tertiary-container": "#ffe0cd",
        "on-primary-fixed-variant": "#5a00c6",
        "surface-tint": "#732ee4",
        "surface-container-high": "#e2e8f8",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f9f9ff",
        "surface-variant": "#dce2f3",
        "tertiary-fixed": "#ffdcc6",
        "surface-dim": "#d3daea"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "12px",
        "2xl": "16px",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "40px",
        "base": "8px",
        "gutter": "24px",
        "container-max": "1200px",
        "margin-mobile": "16px"
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "title-lg": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "title-lg": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "display": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
